name: ethereum
description: An ethereum JSON RPC 2.0 client for Dart. Interfaces ethereum API calls to Dart types and vice versa.
version: 4.0.3
homepage: https://github.com/shamblett/ethereum

environment:
  sdk: '>=2.0.0  <3.0.0'

dependencies:
  hex: '^0.1.2'

dev_dependencies:
  test: '^1.14.2'
  pana: '^0.13.5'
  pedantic: '^1.9.0'
  build_runner: '^1.8.0'
  build_test: '^0.10.12+1'
  build_web_compilers: '^2.8.0'

