name: ethereum
description: An ethereum JSON RPC 2.0 client for Dart. Interfaces ethereum API calls to Dart types and vice versa.
version: 4.0.3
homepage: https://github.com/shamblett/ethereum

environment:
  sdk: '>=2.12.0-29.10.beta <3.0.0'

dependencies:
  hex: '^0.1.2'

dev_dependencies:
  test: '^1.16.0-nullsafety.16'
  pana: '^0.14.10'
  pedantic: '^1.10.0-nullsafety.3'
  build_runner: '^1.10.13'
  build_test: '^1.3.4'
  build_web_compilers: '^2.16.0'

