name: ethereum
description: An ethereum JSON RPC 2.0 client for Dart. Interfaces ethereum API calls to Dart types and vice versa.
version: 4.0.0
author: Steve Hamblett <steve.hamblett@linux.com>
homepage: https://github.com/shamblett/ethereum

environment:
  sdk: '>=2.0.0  <3.0.0'

dependencies:
  hex: '^0.1.2'

dev_dependencies:
  test: '^1.3.0'
  coverage: '^0.12.2'
  #dart_dev: '^2.0.0-alpha'
  dart_style: '^1.1.3'
  build_runner: '^1.1.2'
  build_test: '^0.10.2'
  build_web_compilers: '^0.4.0'
