name: ethereum
description: An ethereum JSON RPC 2.0 client for Dart. Interfaces ethereum API calls to Dart types and vice versa.
version: 1.1.0
author: Steve Hamblett <steve.hamblett@linux.com>
homepage: https://github.com/shamblett/ethereum

environment:
  sdk: ">=1.8.0  <2.0.0"

dependencies:
 bignum: any
 

dev_dependencies:
  test: '^0.12.0'
  coverage: '^0.7.3'
  dart_dev: '^1.0.0'
  dart_style: '>=0.2.0 <0.3.0'
  dartdoc: '>=0.8.0 <=0.10.0'

web:
  compiler:
    debug: dartdevc

transformers:
- test/pub_serve:
    $include: test/ethereum_browser_*_test.dart
- $dart2js:
    checked: true
    csp: true
    minify: true
    sourceMaps: true
    suppressHints: true
    suppressWarnings: true
    terse: true
    verbose: true